
image: Visual Studio 2017
configuration: AppVeyor
platform: Any CPU
skip_tags: true

environment:
  mdix_version: 2.5.1
  mdix_mahapps_version: 0.0.13
  mdix_colors_version: 1.1.4

assembly_info:
  patch: false

before_build:
- ps: .paket\paket.exe restore

build_script:
- ps: >-
    msbuild MaterialDesignToolkit.Wpf.sln /property:Configuration=AppVeyor /property:MDIX_CORE_VERSION=$env:mdix_version.$env:APPVEYOR_BUILD_NUMBER /property:MDIX_COLORS_VERSION=$env:mdix_colors_version.$env:APPVEYOR_BUILD_NUMBER /property:MDIX_MAHAPPS_VERSION=$env:mdix_mahapps_version.$env:APPVEYOR_BUILD_NUMBER /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- vstest.console /logger:Appveyor "MaterialDesignThemes.Wpf.Tests\bin\Release\MaterialDesignThemes.Wpf.Tests.dll"


artifacts:
- path: '**\MaterialDesign*.nupkg'
- path: Demo.*.zip

for:
-
  branches:
    only:
      - master
  version: $(mdix_version)-ci{build}
  after_build:
  - ps: >-
      7z a Demo.$($env:mdix_version)-ci$($env:APPVEYOR_BUILD_NUMBER).zip MainDemo.Wpf\bin\**\*.*
      
      nuget pack MaterialDesignThemes.nuspec -Version $env:mdix_version-ci$($env:APPVEYOR_BUILD_NUMBER)
      
      nuget pack MaterialDesignThemes.MahApps.nuspec -Version $env:mdix_mahapps_version-ci$($env:APPVEYOR_BUILD_NUMBER)
      
      nuget pack MaterialDesignColors.nuspec -Version $env:mdix_colors_version-ci$($env:APPVEYOR_BUILD_NUMBER)
  deploy:
  - provider: NuGet
    api_key:
      secure: B+WIdbRYr/rJo1QMeDwNen2xcj4RTu1d8AZiA03kb8wsWZVQxt5OgsWRacmEjWRd
    artifact: /MaterialDesignThemes\..+-ci\d+\.nupkg/

-
  branches:
    only:
      - release
  version: $(mdix_version).{build}
  after_build:
  - ps: >-
      7z a Demo.$($env:mdix_version).zip MainDemo.Wpf\bin\**\*.*
      
      nuget pack MaterialDesignThemes.nuspec -Version $env:mdix_version
      
      nuget pack MaterialDesignThemes.MahApps.nuspec -Version $env:mdix_mahapps_version
      
      nuget pack MaterialDesignColors.nuspec -Version $env:mdix_colors_version
